<?php

namespace ICGM2\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * documentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class documentsRepository extends EntityRepository
{
}
