<?php

namespace ICGM2\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PendingEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PendingEventRepository extends EntityRepository
{

    public function getNb($id)
    {
        return $this->createQueryBuilder('events')
                        ->select('COUNT(events)')
                        ->where('events.eventId = :selectedId')
                        ->setParameter('selectedId', $id)
                        ->getQuery()
                        ->getSingleScalarResult()
        ;
    }

}
