<?php

namespace ICGM2\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * todosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class todosRepository extends EntityRepository
{
}
