<?php

namespace Proxies\__CG__\ICGM2\PagesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class histories extends \ICGM2\PagesBundle\Entity\histories implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'id', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'userId', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'action', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'featuresId', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'featuresName', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'createdTime', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'modifiedTime');
        }

        return array('__isInitialized__', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'id', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'userId', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'action', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'featuresId', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'featuresName', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'createdTime', '' . "\0" . 'ICGM2\\PagesBundle\\Entity\\histories' . "\0" . 'modifiedTime');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (histories $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', array($userId));

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAction($action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAction', array($action));

        return parent::setAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function getAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAction', array());

        return parent::getAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeaturesId($featuresId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeaturesId', array($featuresId));

        return parent::setFeaturesId($featuresId);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeaturesId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeaturesId', array());

        return parent::getFeaturesId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeaturesName($featuresName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeaturesName', array($featuresName));

        return parent::setFeaturesName($featuresName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeaturesName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeaturesName', array());

        return parent::getFeaturesName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedTime($createdTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedTime', array($createdTime));

        return parent::setCreatedTime($createdTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedTime', array());

        return parent::getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedTime($modifiedTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedTime', array($modifiedTime));

        return parent::setModifiedTime($modifiedTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedTime', array());

        return parent::getModifiedTime();
    }

}
